nouns = nouns.concat([
    'restaurant',
    'store',
    'shop',
    'beer',
    'boot',
    'beetle',
    'candle',
    'foot',
    'shoe',
    'medication',
    'saxophone',
    'giraffe',
    'pencil',
    'pen',
    'armpit',
    'bunion',
    'toenail',
    'papier-mache',
    'sandstorm',
    'desert',
    'eyeball',
    'toilet paper',
    'rocket launcher',
    'space ship'
]);